version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin_pizza
      - POSTGRES_PASSWORD=admin_pizza
      - POSTGRES_DB=pizza_database
  
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis